### ISSUE TITLE
No hay definición del proyecto

### ISSUE THREAD

**Issue by norman-ipn** [danalovil/Proyecto_Est-Dat#4]
No hay nada que revisar.
En caso de querer continuar con el proyecto contestar este issue.

@danalovil 
@Piripituchi 
@0draS0

**Comment by danalovil** [comment]
Buenas tardes, profesor.

Si vamos a continuar con este proyecto. Estamos preparando la documentacion para delimitarlo. Lo tendremos listo a mas tardar en dos dias.

Saludos.

**Comment by danalovil** [comment]
> No hay nada que revisar.
> En caso de querer continuar con el proyecto contestar este issue.
> 
> @danalovil
> @Piripituchi
> @0draS0

Buenas tardes, profesor.

Si vamos a continuar con este proyecto. Estamos preparando la documentacion para delimitarlo. Lo tendremos listo a mas tardar en dos dias.

Saludos.

**Comment by norman-ipn** [comment]
Me avisan cuando suban algo del proyecto.
