### ISSUE TITLE
Proyecto Final Estructuras de Datos

### ISSUE THREAD

**Issue by danalovil** [danalovil/Proyecto_Est-Dat#5]
Buenas tardes, compañeros.

Les comparto mi propuesta de formato para el proyecto. Saludos.

Proyecto XXXXXXX
Estructuras de Datos
Profesor: Norman
Integrantes
Introducción
- Qué es una estructura
- Tipos de estructura
- Diferencias entre tipos de estructura
Definición del proyecto.
- Justificación del proyecto
Desarrollo del proyecto
- Pruebas del proyecto
- Retroalimentación
- Proyecto final

**Comment by eduardohdez98** [comment]
Perfecto, aun queda pendiente el nombre
