### ISSUE TITLE
PROYECTO 

### ISSUE THREAD

**Issue by odrasanchezdev** [danalovil/Proyecto_Est-Dat#7]
Hola, he subido lo que tenemos del proyecto. Cada quien lo analiza y debe dar su propuesta/solución a la programación. Además debemos de acordar como podemos hacerlo más comprensible respecto al código

@danalovil 
@Piripituchi

**Comment by danalovil** [comment]
Gracias, Odrita. Lo checo y vamos viendo qué le agregamos. Gracias.

**Comment by eduardohdez98** [comment]
Revisado
